#!/usr/bin/env python3
"""Reference-trace probing for RealBench spec-induction CEGIS.

This script treats the official RealBench reference module as a black-box
oracle. It does not parse the reference RTL. It compiles a small testbench that
drives the public stimulus generator, records top-level reference I/O traces,
and writes a compact induced-spec note for later LLM repair prompts.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Iterable, List


ROOT = Path(__file__).resolve().parents[1]
AES_SYSTEM = ROOT / "system" / "aes_cipher_top"

TRACE_RE = re.compile(
    r"RB_TRACE cycle=(?P<cycle>\d+) time=(?P<time>\d+) "
    r"rst=(?P<rst>[01]) ld=(?P<ld>[01]) done=(?P<done>[01]) "
    r"key=(?P<key>[0-9a-fA-F]+) text_in=(?P<text_in>[0-9a-fA-F]+) "
    r"text_out=(?P<text_out>[0-9a-fA-F]+)"
)


TRACE_TB = r"""`timescale 1 ps/1 ps

module tb();
    reg clk = 0;
    initial forever #5 clk = ~clk;

    logic rst, ld;
    logic [127:0] key;
    logic [127:0] text_in;
    logic done;
    logic [127:0] text_out;
    logic [511:0] wavedrom_title;
    logic wavedrom_enable;
    int cycle;

    stimulus_gen stim1 (
        .clk(clk),
        .tb_match(1'b1),
        .rst(rst),
        .ld(ld),
        .key(key),
        .text_in(text_in),
        .wavedrom_title(wavedrom_title),
        .wavedrom_enable(wavedrom_enable)
    );

    ref_aes_cipher_top ref1 (
        .clk(clk),
        .rst(rst),
        .ld(ld),
        .done(done),
        .key(key),
        .text_in(text_in),
        .text_out(text_out)
    );

    always @(posedge clk) begin
        cycle++;
        $display("RB_TRACE cycle=%0d time=%0t rst=%0b ld=%0b done=%0b key=%032h text_in=%032h text_out=%032h",
                 cycle, $time, rst, ld, done, key, text_in, text_out);
    end

    initial begin
        #1000000;
        $display("RB_TRACE_TIMEOUT");
        $finish;
    end
endmodule
"""


def _parse_traces(stdout: str) -> List[dict]:
    rows = []
    for line in stdout.splitlines():
        m = TRACE_RE.search(line)
        if not m:
            continue
        d = m.groupdict()
        rows.append(
            {
                "cycle": int(d["cycle"]),
                "time": int(d["time"]),
                "rst": int(d["rst"]),
                "ld": int(d["ld"]),
                "done": int(d["done"]),
                "key": d["key"].lower().zfill(32),
                "text_in": d["text_in"].lower().zfill(32),
                "text_out": d["text_out"].lower().zfill(32),
            }
        )
    return rows


def _window(rows: List[dict], start: int, width: int = 16) -> List[dict]:
    return [r for r in rows if start <= r["cycle"] < start + width]


def _load_windows(rows: List[dict], width: int = 16, limit: int = 8) -> List[dict]:
    out = []
    prev = None
    for row in rows:
        changed_inputs = (
            prev is not None
            and (row["key"] != prev["key"] or row["text_in"] != prev["text_in"])
        )
        if row["ld"] == 1 or changed_inputs:
            out.append(
                {
                    "start_cycle": row["cycle"],
                    "key": row["key"],
                    "text_in": row["text_in"],
                    "trace": _window(rows, row["cycle"], width),
                }
            )
        if len(out) >= limit:
            break
        prev = row
    return out


def _reset_windows(rows: List[dict], width: int = 8, limit: int = 4) -> List[dict]:
    out = []
    prev_rst = None
    for row in rows:
        if row["rst"] == 0 and prev_rst != 0:
            out.append({"start_cycle": row["cycle"], "trace": _window(rows, row["cycle"], width)})
        prev_rst = row["rst"]
        if len(out) >= limit:
            break
    return out


def _summarize(rows: List[dict]) -> dict:
    done_cycles = [r["cycle"] for r in rows if r["done"] == 1]
    unique_text = len({r["text_out"] for r in rows})
    load_windows = _load_windows(rows)
    reset_windows = _reset_windows(rows)
    return {
        "num_cycles": len(rows),
        "first_cycle": rows[0] if rows else None,
        "first_20": rows[:20],
        "unique_text_out_values": unique_text,
        "done_cycles": done_cycles[:32],
        "reset_windows": reset_windows,
        "load_windows": load_windows,
    }


def _row_line(row: dict, rel_to: int | None = None) -> str:
    prefix = f"c{row['cycle']}"
    if rel_to is not None:
        prefix += f"/+{row['cycle'] - rel_to}"
    return (
        f"- {prefix}: rst={row['rst']} ld={row['ld']} done={row['done']} "
        f"key={row['key']} text_in={row['text_in']} text_out={row['text_out']}"
    )


def _write_md(summary: dict, path: Path) -> None:
    lines = [
        "# RealBench AES Induced Spec Notes",
        "",
        "Generated by black-box probing of `ref_aes_cipher_top` with the public RealBench stimulus generator.",
        "The final judge remains the original RealBench system testbench.",
        "",
        f"- Recorded cycles: {summary['num_cycles']}",
        f"- Unique `text_out` values observed: {summary['unique_text_out_values']}",
        f"- First `done=1` cycles: {summary['done_cycles'][:16]}",
        "",
        "## First 20 Cycles",
    ]
    lines.extend(_row_line(r) for r in summary["first_20"])
    lines += ["", "## Reset Windows"]
    for idx, win in enumerate(summary["reset_windows"]):
        lines.append(f"### Reset Window {idx} starting cycle {win['start_cycle']}")
        lines.extend(_row_line(r, win["start_cycle"]) for r in win["trace"])
    lines += ["", "## Load Windows"]
    for idx, win in enumerate(summary["load_windows"]):
        lines.append(
            f"### Load Window {idx} starting cycle {win['start_cycle']} "
            f"key={win['key']} text_in={win['text_in']}"
        )
        lines.extend(_row_line(r, win["start_cycle"]) for r in win["trace"])
    lines += [
        "",
        "## Repair-Relevant Facts",
        "- `text_out` is checked every clock, not only when `done=1`.",
        "- The reference exposes intermediate visible states on `text_out` during reset, idle, and encryption.",
        "- A final-ciphertext-only implementation is structurally mismatched against this benchmark.",
        "- Repair should match reset/idle visible-state behavior, load-to-round timing, state byte layout, key schedule timing, and `done` pulse timing.",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _copy_tree(src: Path, dst: Path) -> None:
    for path in src.iterdir():
        if path.is_file():
            shutil.copy2(path, dst / path.name)


def probe_aes_reference(args: argparse.Namespace) -> int:
    if not AES_SYSTEM.exists():
        raise SystemExit(f"missing AES system dir: {AES_SYSTEM}")
    runtime_root = Path(f"/run/user/{os.getuid()}")
    tmp_parent = runtime_root if runtime_root.exists() else None
    with tempfile.TemporaryDirectory(dir=tmp_parent) as td:
        work = Path(td)
        _copy_tree(AES_SYSTEM, work)
        candidate_top = work / "aes_cipher_top_top.sv"
        if candidate_top.exists():
            candidate_top.unlink()
        (work / "aes_cipher_top_testbench.sv").write_text(TRACE_TB, encoding="utf-8")
        proc = subprocess.run(
            "make all",
            cwd=work,
            shell=True,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            timeout=args.timeout,
        )
        rows = _parse_traces(proc.stdout)
        if not rows:
            if proc.returncode != 0:
                raise SystemExit(f"trace probe failed rc={proc.returncode}\n{proc.stdout[-4000:]}")
            raise SystemExit(f"trace probe produced no RB_TRACE rows\n{proc.stdout[-4000:]}")

    summary = _summarize(rows)
    out_json = Path(args.out_json)
    out_md = Path(args.out_md)
    out_json.parent.mkdir(parents=True, exist_ok=True)
    out_json.write_text(
        json.dumps({"traces": rows, "summary": summary}, indent=2),
        encoding="utf-8",
    )
    _write_md(summary, out_md)
    print(f"wrote {len(rows)} trace rows to {out_json}")
    print(f"wrote induced spec notes to {out_md}")
    return 0


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    sub = parser.add_subparsers(dest="cmd", required=True)

    probe = sub.add_parser("probe-aes-reference")
    probe.add_argument("--out-json", default="realbench-results/aes-reference-traces.json")
    probe.add_argument("--out-md", default="realbench-results/aes-spec-induction.md")
    probe.add_argument("--timeout", type=int, default=600)
    probe.set_defaults(func=probe_aes_reference)

    args = parser.parse_args(list(argv) if argv is not None else None)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
